### ISSUE TITLE
Add tags to this repo?

### ISSUE THREAD

**Issue by kclejeune** [kovidgoyal/kitty-themes#29]
Based on https://github.com/NixOS/nixpkgs/pull/153505 -- would you be willing to add tagged versions to this repo? They don't even need to correspond to releases, just `v0.1.0` or something on the current default branch would be great.

**Comment by kovidgoyal** [comment]
Not sure I follow. This repo is not meant to be packaged. It is
downloaded directly by the kitty themes kitten. What is the point of
packaging it in nix?

**Comment by kovidgoyal** [comment]
no followup

**Comment by NelsonJeppesen** [comment]
> Not sure I follow. This repo is not meant to be packaged. It is downloaded directly by the kitty themes kitten. What is the point of packaging it in nix?

I'm not the OP but can guess the reasons

I opened the linked PR to nixos and recently created this merged https://github.com/nix-community/home-manager/pull/2710 to home-manager

NixOS is declarative configured Linux distro; home-manager runs on top of that to manager dot files and other user configuration

As such, the kitty configuration file is read-only because it's generated and managed by Nix. This is why I added kitty themes to the NixOS repo.

This is what a kitty config looks like in nixos/home-manager
https://github.com/NelsonJeppesen/nix-lifestyle/blob/main/nixpkgs/kitty.nix

**Comment by NelsonJeppesen** [comment]
> Is there some reason you cant use a commit hash for that? A tag is just
> an alias for a commit hash. And this repo does not have "releases"
> 

Totally, no problem at all. That's what it's doing now without an issues

Just wanted to share some context on nix.

Personally I have no desire for a version tag, but it didn't create this issue so don't want to say anything

**Comment by kclejeune** [comment]
@kovidgoyal @NelsonJeppesen sorry for confusion on this! I didn't realize that you weren't intending to have releases on this repo (it wasn't stated anywhere in the docs). Since we generally prefer tags over commit refs in nixpkgs, I figured it wouldn't hurt to ask. I meant to close the issue after your original clarifying comment but evidently I forgot.
